/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'men' : IDL.Null,
  'newIn' : IDL.Null,
  'women' : IDL.Null,
});
export const Badge = IDL.Variant({
  'hot' : IDL.Null,
  'new' : IDL.Null,
  'sale' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'badge' : IDL.Opt(Badge),
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addItemToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'clearCart' : IDL.Func([IDL.Text], [], []),
  'clearWishlist' : IDL.Func([], [], []),
  'createCart' : IDL.Func([IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCartItems' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  'removeItemFromCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'seedProducts' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'men' : IDL.Null,
    'newIn' : IDL.Null,
    'women' : IDL.Null,
  });
  const Badge = IDL.Variant({
    'hot' : IDL.Null,
    'new' : IDL.Null,
    'sale' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'badge' : IDL.Opt(Badge),
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  
  return IDL.Service({
    'addItemToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'clearCart' : IDL.Func([IDL.Text], [], []),
    'clearWishlist' : IDL.Func([], [], []),
    'createCart' : IDL.Func([IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCartItems' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
    'removeItemFromCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'seedProducts' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };