/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CartItem {
    productId: bigint;
    quantity: bigint;
}
export interface Product {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    imageUrl: string;
    category: Category;
    badge?: Badge;
    price: bigint;
}
export enum Badge {
    hot = "hot",
    new_ = "new",
    sale = "sale"
}
export enum Category {
    men = "men",
    newIn = "newIn",
    women = "women"
}
export interface backendInterface {
    addItemToCart(cartId: string, productId: bigint, quantity: bigint): Promise<void>;
    addToWishlist(productId: bigint): Promise<void>;
    clearCart(cartId: string): Promise<void>;
    clearWishlist(): Promise<void>;
    createCart(cartId: string): Promise<void>;
    getAllProducts(): Promise<Array<Product>>;
    getCartItems(cartId: string): Promise<Array<CartItem>>;
    getProductById(productId: bigint): Promise<Product>;
    getProductsByCategory(category: Category): Promise<Array<Product>>;
    getWishlist(): Promise<Array<bigint>>;
    removeFromWishlist(productId: bigint): Promise<void>;
    removeItemFromCart(cartId: string, productId: bigint): Promise<void>;
    seedProducts(): Promise<void>;
}
import type { Badge as _Badge, Category as _Category, Product as _Product } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addItemToCart(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addItemToCart(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItemToCart(arg0, arg1, arg2);
            return result;
        }
    }
    async addToWishlist(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async clearCart(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart(arg0);
            return result;
        }
    }
    async clearWishlist(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearWishlist();
            return result;
        }
    }
    async createCart(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCart(arg0);
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCartItems(arg0: string): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCartItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCartItems(arg0);
            return result;
        }
    }
    async getProductById(arg0: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_Product_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_Product_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: Category): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_Category_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_Category_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWishlist(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async removeFromWishlist(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async removeItemFromCart(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeItemFromCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeItemFromCart(arg0, arg1);
            return result;
        }
    }
    async seedProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedProducts();
            return result;
        }
    }
}
function from_candid_Badge_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Badge): Badge {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Badge]): Badge | null {
    return value.length === 0 ? null : from_candid_Badge_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    imageUrl: string;
    category: _Category;
    badge: [] | [_Badge];
    price: bigint;
}): {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    imageUrl: string;
    category: Category;
    badge?: Badge;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        imageUrl: value.imageUrl,
        category: from_candid_Category_n4(_uploadFile, _downloadFile, value.category),
        badge: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.badge)),
        price: value.price
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    men: null;
} | {
    newIn: null;
} | {
    women: null;
}): Category {
    return "men" in value ? Category.men : "newIn" in value ? Category.newIn : "women" in value ? Category.women : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hot: null;
} | {
    new: null;
} | {
    sale: null;
}): Badge {
    return "hot" in value ? Badge.hot : "new" in value ? Badge.new : "sale" in value ? Badge.sale : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    men: null;
} | {
    newIn: null;
} | {
    women: null;
} {
    return value == Category.men ? {
        men: null
    } : value == Category.newIn ? {
        newIn: null
    } : value == Category.women ? {
        women: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
